import {test} from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import ts from "typescript";
const load=(path,deps={},env={})=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,URL,process:{env},console:{warn(){},error(){}},require:name=>deps[name]});return exports;};
test('Contacto comercial configurable, prioridad WhatsApp y fallback seguro',()=>{const file='src/lib/commercial-contact.ts';assert.equal(load(file).commercialContact(),null);assert.equal(load(file,{},{NEXT_PUBLIC_TIKITAKA_EMAIL:'bad\r\naddress',NEXT_PUBLIC_TIKITAKA_WHATSAPP:'javascript:evil'}).commercialContact(),null);assert.match(load(file,{},{NEXT_PUBLIC_TIKITAKA_EMAIL:'support@example.test'}).commercialContact('A & B'),/^mailto:support@example.test\?subject=A%20%26%20B/);assert.match(load(file,{},{NEXT_PUBLIC_TIKITAKA_EMAIL:'support@example.test',NEXT_PUBLIC_TIKITAKA_WHATSAPP:'+54 9 11 1234 5678'}).commercialContact(),/^https:\/\/wa.me\/5491112345678\?text=/);});
test('URL de sitio no permite desplegar Vercel sin dominio ni usar localhost en producción',()=>{const f='src/lib/site-url.ts';assert.equal(load(f).getSiteUrl(),'http://localhost:3000');assert.throws(()=>load(f,{},{VERCEL_ENV:'production'}).getSiteUrl());assert.throws(()=>load(f,{},{VERCEL_ENV:'production',NEXT_PUBLIC_SITE_URL:'http://localhost:3000'}).getSiteUrl());assert.throws(()=>load(f,{},{NEXT_PUBLIC_SITE_URL:'https://user:secret@example.test'}).getSiteUrl());assert.equal(load(f,{},{VERCEL_ENV:'production',NEXT_PUBLIC_SITE_URL:'https://example.test/'}).getSiteUrl(),'https://example.test');});
class ResponseMock{constructor(body,init={}){this.body=body;this.status=init.status??200;}static json(body,init){return new ResponseMock(body,init);}}
function contacts(fail=false){const writes=[];const route=load('src/app/api/contact-events/route.ts',{'next/server':{NextResponse:ResponseMock},'@/lib/data/contact-events':{CONTACT_EVENT_SOURCES:['marketplace_card','provider_profile','sticky_contact'],createContactEvent:async b=>{if(fail)throw new Error('DB internal');writes.push(b);}}});return {writes,post:body=>route.POST({json:async()=>body})};}
test('Tracking responde 204 solo al persistir y acepta las tres fuentes reales',async()=>{const h=contacts();for(const source of ['marketplace_card','provider_profile','sticky_contact'])assert.equal((await h.post({providerId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',source,page:'/servicios'})).status,204);assert.equal(h.writes.length,3);});
test('Fallo de persistencia no se disfraza de éxito y payload nulo se rechaza',async()=>{assert.equal((await contacts(true).post({providerId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',source:'provider_profile'})).status,503);const h=contacts();assert.equal((await h.post(null)).status,400);assert.equal((await h.post({source:'admin'})).status,400);assert.equal(h.writes.length,0);});
test('Rating persistido filtra aprobadas/publicadas y pagina sin truncar',async()=>{const calls=[],updates=[];const db={from(table){const filters=[];calls.push({table,filters});let range=[0,499];return{select(){return this;},eq(k,v){filters.push([k,v]);return this;},order(){return this;},range(a,b){range=[a,b];return this;},update(patch){updates.push(patch);return this;},then(resolve){return Promise.resolve(table==='reviews'?{data:Array.from({length:501},()=>({rating:4})).slice(range[0],range[1]+1),error:null}:{error:null}).then(resolve);}}}};const mod=load('src/lib/data/reviews.ts',{'@/lib/supabase/admin':{createAdminClient:()=>db}});await mod.recalculateProviderRating('owner');assert.equal(updates[0].reviews_count,501);assert.equal(updates[0].rating,4);for(const call of calls.filter(c=>c.table==='reviews')){assert(call.filters.some(([k,v])=>k==='provider_id'&&v==='owner'));assert(call.filters.some(([k,v])=>k==='status'&&v==='approved'));assert(call.filters.some(([k,v])=>k==='published'&&v===true));}});
