"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { categories, providers } from "@/lib/mock-data";

export function SmartSearch() {
  const router = useRouter(); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  const term = query.trim().toLocaleLowerCase("es");
  const suggestions = useMemo(() => ({ categories: term ? categories.filter((item) => item.name.toLocaleLowerCase("es").includes(term)).slice(0, 3) : categories.slice(0, 3), providers: term ? providers.filter((item) => `${item.name} ${item.category}`.toLocaleLowerCase("es").includes(term)).slice(0, 3) : [], zones: term ? [...new Set(providers.map((item) => item.zone))].filter((zone) => zone.toLocaleLowerCase("es").includes(term)).slice(0, 3) : [] }), [term]);
  const submit = (event: FormEvent) => { event.preventDefault(); router.push(`/servicios${query ? `?q=${encodeURIComponent(query)}` : ""}`); setOpen(false); };
  const show = open && (suggestions.categories.length + suggestions.providers.length + suggestions.zones.length > 0);
  return <form onSubmit={submit} className="relative mt-8 max-w-2xl"><div className="flex flex-col gap-2 rounded-3xl bg-white p-2 soft-shadow sm:flex-row"><label className="flex flex-1 items-center gap-3 px-4"><span className="text-xl text-brand">⌕</span><input value={query} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onFocus={() => setOpen(true)} onBlur={() => window.setTimeout(() => setOpen(false), 150)} name="q" autoComplete="off" className="w-full py-3 text-sm outline-none" placeholder="¿Qué servicio estás buscando?" /></label><div className="hidden border-l border-teal-900/10 sm:block" /><label className="flex items-center gap-2 px-4 text-sm font-bold"><span>⌖</span><select className="bg-transparent py-3 outline-none" aria-label="Zona"><option>Buenos Aires</option></select></label><button className="rounded-2xl bg-brand px-6 py-4 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-brand-dark">Buscar servicios</button></div>
    {show && <div className="absolute inset-x-0 top-full z-30 mt-3 overflow-hidden rounded-2xl border border-teal-900/8 bg-white p-3 text-left shadow-2xl"><SuggestionGroup title="Categorías">{suggestions.categories.map((item) => <Link key={item.slug} href={`/categorias/${item.slug}`} className="flex items-center gap-3 rounded-xl p-3 text-sm hover:bg-mint"><span className={`grid h-8 w-8 place-items-center rounded-lg ${item.color}`}>{item.icon}</span><span className="font-bold">{item.name}</span></Link>)}</SuggestionGroup>{suggestions.providers.length > 0 && <SuggestionGroup title="Proveedores">{suggestions.providers.map((item) => <Link key={item.id} href={`/proveedores/${item.slug}`} className="block rounded-xl p-3 text-sm hover:bg-mint"><span className="font-bold">{item.name}</span><span className="ml-2 text-xs text-muted">{item.category} · {item.zone}</span></Link>)}</SuggestionGroup>}{suggestions.zones.length > 0 && <SuggestionGroup title="Zonas">{suggestions.zones.map((zone) => <button type="button" key={zone} onMouseDown={() => { setQuery(zone); router.push(`/servicios?q=${encodeURIComponent(zone)}`); }} className="block w-full rounded-xl p-3 text-left text-sm font-bold hover:bg-mint">⌖ {zone}</button>)}</SuggestionGroup>}<button type="submit" className="mt-2 w-full rounded-xl bg-mint p-3 text-sm font-extrabold text-brand">Ver todos los resultados para “{query || "servicios"}” →</button></div>}
  </form>;
}
function SuggestionGroup({ title, children }: { title: string; children: React.ReactNode }) { return <div className="border-b border-teal-900/6 py-2 last:border-0"><p className="px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.16em] text-muted">{title}</p>{children}</div>; }
