"use client";

import { useRef, useState } from "react";
import type { AccountImage, AccountProvider } from "@/lib/auth/account";

const allowed = new Set(["image/jpeg", "image/png", "image/webp"]); const maxSize = 5 * 1024 * 1024;
export function PhotosEditor({ provider, images: initialImages }: { provider: AccountProvider; images: AccountImage[] }) {
  const [cover,setCover]=useState(provider.coverImage);const[logo,setLogo]=useState(provider.logo);const[images,setImages]=useState(initialImages);const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);const galleryInput=useRef<HTMLInputElement>(null);
  const validate=(file:File)=>{if(!allowed.has(file.type))return "Solo se permiten imágenes JPG, PNG o WEBP.";if(file.size>maxSize)return "Cada imagen debe pesar como máximo 5 MB.";return null;};
  const upload=async(file:File,kind:"cover"|"logo"|"gallery")=>{const error=validate(file);if(error){setMessage({type:"error",text:error});return null;}const data=new FormData();data.append("file",file);data.append("kind",kind);const response=await fetch("/api/dashboard/images",{method:"POST",body:data});const result=await response.json();if(!response.ok){setMessage({type:"error",text:result.error||"No se pudo subir la imagen."});return null;}return result;};
  const uploadSingle=async(file:File|undefined,kind:"cover"|"logo")=>{if(!file)return;const previous=kind==="cover"?cover:logo;const preview=URL.createObjectURL(file);if(kind==="cover")setCover(preview);else setLogo(preview);setBusy(kind);setMessage(null);const result=await upload(file,kind);if(result){if(kind==="cover")setCover(result.url);else setLogo(result.url);setMessage({type:"success",text:kind==="cover"?"Imagen principal actualizada.":"Logo actualizado."});}else if(kind==="cover")setCover(previous);else setLogo(previous);URL.revokeObjectURL(preview);setBusy(null);};
  const uploadGallery=async(files:FileList|null)=>{if(!files?.length)return;if(images.length+files.length>8){setMessage({type:"error",text:"La galería admite un máximo de 8 imágenes."});return;}setBusy("gallery");setMessage(null);let added=0;for(const file of Array.from(files)){const result=await upload(file,"gallery");if(result?.image){setImages((current)=>[...current,result.image]);added++;}else break;}if(added)setMessage({type:"success",text:`${added} ${added===1?"imagen cargada":"imágenes cargadas"} en la galería.`});if(galleryInput.current)galleryInput.current.value="";setBusy(null);};
  const remove=async(image:AccountImage)=>{setBusy(image.id);setMessage(null);const response=await fetch("/api/dashboard/images",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageId:image.id})});const result=await response.json();if(response.ok){setImages((current)=>current.filter((item)=>item.id!==image.id));setMessage({type:"success",text:"Imagen eliminada."});}else setMessage({type:"error",text:result.error||"No se pudo eliminar."});setBusy(null);};
  return <div className="mt-8 space-y-7"><div className="grid gap-6 md:grid-cols-2"><UploadCard title="Imagen principal" text="Se usa en el catálogo y como portada del perfil." url={cover} busy={busy==="cover"} onFile={(file)=>uploadSingle(file,"cover")}/><UploadCard title="Logo" text="Identidad visual de tu negocio." url={logo} busy={busy==="logo"} onFile={(file)=>uploadSingle(file,"logo")} contain/></div><section className="rounded-[1.75rem] bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="display text-3xl font-semibold">Galería</h2><p className="mt-2 text-sm text-muted">Hasta 8 imágenes. JPG, PNG o WEBP; máximo 5 MB cada una.</p></div><label className={`cursor-pointer rounded-full bg-brand px-5 py-3 text-sm font-extrabold text-white ${busy==="gallery"||images.length>=8?"pointer-events-none opacity-50":""}`}>{busy==="gallery"?"Subiendo…":"Agregar imágenes"}<input ref={galleryInput} type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event)=>uploadGallery(event.target.files)}/></label></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{images.map((image,index)=><article key={image.id} className="group relative overflow-hidden rounded-2xl bg-slate-100"><div className="h-44 bg-cover bg-center" style={{backgroundImage:`url(${JSON.stringify(image.imageUrl).slice(1,-1)})`}}/><span className="absolute left-3 top-3 rounded-full bg-white/90 px-2 py-1 text-[10px] font-extrabold">{index+1}</span><button disabled={busy===image.id} onClick={()=>remove(image)} className="absolute right-3 top-3 rounded-full bg-white px-3 py-1.5 text-xs font-extrabold text-rose-700 shadow disabled:opacity-50">Eliminar</button></article>)}{!images.length&&<div className="col-span-full rounded-2xl border border-dashed border-brand/30 bg-mint p-10 text-center text-sm text-muted">Todavía no agregaste imágenes a la galería.</div>}</div></section>{message&&<p role="status" className={`rounded-xl p-4 text-sm font-bold ${message.type==="success"?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{message.text}</p>}<div className="rounded-xl bg-lilac p-4 text-sm text-muted">Las imágenes se almacenan de forma segura en Supabase Storage dentro de la carpeta de tu cuenta.</div></div>;
}

function UploadCard({title,text,url,busy,onFile,contain=false}:{title:string;text:string;url:string;busy:boolean;onFile:(file:File|undefined)=>void;contain?:boolean}){return <section className="rounded-[1.75rem] bg-white p-6 shadow-sm"><h2 className="display text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm text-muted">{text}</p><div className={`mt-5 h-52 rounded-2xl bg-slate-100 bg-center bg-no-repeat ${contain?"bg-contain":"bg-cover"}`} style={url?{backgroundImage:`url(${JSON.stringify(url).slice(1,-1)})`}:undefined}>{busy&&<div className="grid h-full place-items-center rounded-2xl bg-white/70 text-sm font-extrabold text-brand backdrop-blur">Subiendo imagen…</div>}</div><label className={`mt-5 inline-flex cursor-pointer rounded-full border-2 border-brand px-5 py-2.5 text-sm font-extrabold text-brand ${busy?"pointer-events-none opacity-50":""}`}>{url?"Cambiar imagen":"Subir imagen"}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event)=>onFile(event.target.files?.[0])}/></label></section>}
