"use client";

import { geographicDraft, validGeography } from "@/lib/geography";
import { GeographyFields } from "@/components/geography-fields";
import { FormEvent, useState } from "react";
import { createBrowserClient } from "@/lib/supabase/client";
import type { AccountProvider } from "@/lib/auth/account";
import type { Category } from "@/types";

export function ProfileForm({ provider, categories }: { provider: AccountProvider; categories: Category[] }) {
  const [form, setForm] = useState(() => geographicDraft(provider)); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const set = (key: keyof AccountProvider, value: string | number) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!validGeography(form.zone, form.city)) { setMessage("Seleccioná una zona y localidad válidas."); return; } setBusy(true); setMessage(""); const supabase = createBrowserClient(); if (!supabase) { setMessage("Supabase no está configurado."); setBusy(false); return; } const { error } = await supabase.from("providers").update({ business_name: form.businessName, description: form.description, category_id: form.categoryId || null, zone: form.zone, city: form.city, province: form.province, address: form.address, whatsapp: form.whatsapp, email: form.email, price_from: form.priceFrom, schedule: form.schedule, coverage: form.coverage }).eq("id", provider.id); setMessage(error ? `Error: ${error.message}` : "Cambios guardados correctamente."); setBusy(false); };
  const fields: [string, keyof AccountProvider, string?][] = [["Nombre del negocio", "businessName"], ["Provincia", "province"], ["Dirección", "address"], ["WhatsApp", "whatsapp"], ["Email", "email", "email"], ["Precio desde", "priceFrom", "number"], ["Horarios", "schedule"], ["Cobertura", "coverage"]];
  return <form onSubmit={submit} className="mt-8 rounded-[1.75rem] bg-white p-6 shadow-sm"><div className="grid gap-5 md:grid-cols-2"><GeographyFields value={form} onChange={value => setForm(current => ({ ...current, ...value }))} required />{fields.map(([label, key, type]) => <label key={key} className="text-sm font-extrabold">{label}<input type={type || "text"} value={String(form[key] ?? "")} onChange={(event) => set(key, type === "number" ? Number(event.target.value) : event.target.value)} className="mt-2 w-full rounded-xl border border-teal-900/10 p-3 font-normal outline-brand" /></label>)}<label className="text-sm font-extrabold">Categoría<select value={form.categoryId ?? ""} onChange={(event) => set("categoryId", event.target.value)} className="mt-2 w-full rounded-xl border border-teal-900/10 bg-white p-3 font-normal"><option value="">Sin categoría</option>{categories.map((item) => <option key={item.slug} value={item.id ?? ""}>{item.name}</option>)}</select></label><label className="text-sm font-extrabold md:col-span-2">Descripción<textarea rows={6} value={form.description} onChange={(event) => set("description", event.target.value)} className="mt-2 w-full rounded-xl border border-teal-900/10 p-3 font-normal outline-brand" /></label></div>{message && <p className="mt-5 rounded-xl bg-mint p-4 text-sm font-bold text-brand">{message}</p>}<button disabled={busy} className="mt-6 rounded-full bg-brand px-6 py-3 font-extrabold text-white disabled:opacity-60">{busy ? "Guardando…" : "Guardar cambios"}</button></form>;
}
